package com.example.demo;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MFamilyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_family
     *
     * @mbggenerated Fri Jul 13 13:38:53 JST 2018
     */
    int countByExample(MFamilyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_family
     *
     * @mbggenerated Fri Jul 13 13:38:53 JST 2018
     */
    public int deleteByExample(MFamilyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_family
     *
     * @mbggenerated Fri Jul 13 13:38:53 JST 2018
     */
    int deleteByPrimaryKey(Integer familyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_family
     *
     * @mbggenerated Fri Jul 13 13:38:53 JST 2018
     */
    int insert(MFamily record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_family
     *
     * @mbggenerated Fri Jul 13 13:38:53 JST 2018
     */
    int insertSelective(MFamily record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_family
     *
     * @mbggenerated Fri Jul 13 13:38:53 JST 2018
     */
    List<MFamily> selectByExample(MFamilyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_family
     *
     * @mbggenerated Fri Jul 13 13:38:53 JST 2018
     */
    MFamily selectByPrimaryKey(Integer familyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_family
     *
     * @mbggenerated Fri Jul 13 13:38:53 JST 2018
     */
    int updateByExampleSelective(@Param("record") MFamily record, @Param("example") MFamilyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_family
     *
     * @mbggenerated Fri Jul 13 13:38:53 JST 2018
     */
    int updateByExample(@Param("record") MFamily record, @Param("example") MFamilyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_family
     *
     * @mbggenerated Fri Jul 13 13:38:53 JST 2018
     */
    int updateByPrimaryKeySelective(MFamily record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_family
     *
     * @mbggenerated Fri Jul 13 13:38:53 JST 2018
     */
    int updateByPrimaryKey(MFamily record);
}