package com.example.demo;

public class MFamily {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_family.family_id
     *
     * @mbggenerated Fri Jul 13 13:38:53 JST 2018
     */
    private Integer familyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_family.name
     *
     * @mbggenerated Fri Jul 13 13:38:53 JST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_family.family_id
     *
     * @return the value of m_family.family_id
     *
     * @mbggenerated Fri Jul 13 13:38:53 JST 2018
     */
    public Integer getFamilyId() {
        return familyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_family.family_id
     *
     * @param familyId the value for m_family.family_id
     *
     * @mbggenerated Fri Jul 13 13:38:53 JST 2018
     */
    public void setFamilyId(Integer familyId) {
        this.familyId = familyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_family.name
     *
     * @return the value of m_family.name
     *
     * @mbggenerated Fri Jul 13 13:38:53 JST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_family.name
     *
     * @param name the value for m_family.name
     *
     * @mbggenerated Fri Jul 13 13:38:53 JST 2018
     */
    public void setName(String name) {
        this.name = name;
    }
}